<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework> 
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF> 
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ChessCore\**" />
    <EmbeddedResource Remove="ChessCore\**" />
    <None Remove="ChessCore\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="gui\Obrazky\**\*.png" />
    <Resource Include="gui\Obrazky\**\*.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="ChessCore\ChessCore.csproj" />
  </ItemGroup>

</Project>